language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
sudo: required
dist: trusty
os:
  - linux
addons:
  apt:
    packages:
      - libcryptsetup-dev
notifications:
  email:
    on_success: never