[package]
name = "cryptsetup-rs"
version = "0.1.2"
authors = ["Vladimir Lushnikov <vladimir@solidninja.is>"]
license = "LGPL-3.0"
description = "Rust wrapper around the libcryptsetup library, allowing manipulation of LUKS devices in Linux"
homepage = "https://github.com/solidninja/cryptsetup-rs"

[lib]
name = "cryptsetup_rs"

[dependencies]
libc = "0.2"
errno = "0.2"
uuid = { version = "0.6", features = ["v4"] }
log = "0.4"

[dependencies.libcryptsetup-sys]
version = "0.1.1"
path = "libcryptsetup-sys"

[dependencies.blkid-rs]
version = "0.1.0"
path = "blkid-rs"

[dev-dependencies]
env_logger = "0.4"
tempdir = "0.3"
expectest = "0.3"

[[test]]
name = "tests"
