[package]
authors = ["Vladimir Lushnikov <vladimir@solidninja.is>"]
description = "Rust wrapper around the libcryptsetup library, allowing manipulation of LUKS devices in Linux"
homepage = "https://github.com/solidninja/cryptsetup-rs"
license = "LGPL-3.0"
name = "cryptsetup-rs"
version = "0.2.0"
[dependencies]
errno = "0.2.4"
libc = "0.2.43"
log = "0.4.4"

[dependencies.blkid-rs]
path = "blkid-rs"
version = "0.2.0"

[dependencies.libcryptsetup-sys]
path = "libcryptsetup-sys"
version = "0.2.0"

[dependencies.uuid]
features = ["v4"]
version = "0.6.5"

[dev-dependencies]
env_logger = "0.5.13"
expectest = "0.10.0"
tempdir = "0.3.7"

[lib]
name = "cryptsetup_rs"
