[package]
name = "blkid-rs"
version = "0.1.0"
authors = ["Vladimir Lushnikov <vladimir@solidninja.is>"]

[lib]
name = "blkid_rs"

[dependencies]
byteorder = "0.5"
uuid = "0.3"

[dev-dependencies]
env_logger = "0.3"
tempdir = "0.3"
